#pragma once

#include <stdint.h>

#if __has_include("FlowerLampConfig.generated.h")
#include "FlowerLampConfig.generated.h"
#endif

#ifndef FLOWER_LAMP_LAMP_PIN
#define FLOWER_LAMP_LAMP_PIN 23
#endif

#ifndef FLOWER_LAMP_MIC_PIN
#define FLOWER_LAMP_MIC_PIN 34
#endif

#ifndef FLOWER_LAMP_MODE_BUTTON_PIN
#define FLOWER_LAMP_MODE_BUTTON_PIN 27
#endif

#ifndef FLOWER_LAMP_PWM_FREQUENCY_HZ
#define FLOWER_LAMP_PWM_FREQUENCY_HZ 1000
#endif

#ifndef FLOWER_LAMP_PWM_RESOLUTION_BITS
#define FLOWER_LAMP_PWM_RESOLUTION_BITS 8
#endif

#ifndef FLOWER_LAMP_MAX_BRIGHTNESS_PERCENT
#define FLOWER_LAMP_MAX_BRIGHTNESS_PERCENT 98
#endif

#ifndef FLOWER_LAMP_BREATH_FLOOR_PERCENT
#define FLOWER_LAMP_BREATH_FLOOR_PERCENT 1
#endif

#ifndef FLOWER_LAMP_STEADY_BRIGHTNESS_PERCENT
#define FLOWER_LAMP_STEADY_BRIGHTNESS_PERCENT 18
#endif

#ifndef FLOWER_LAMP_SAMPLE_WINDOW_MS
#define FLOWER_LAMP_SAMPLE_WINDOW_MS 25
#endif

#ifndef FLOWER_LAMP_CALIBRATION_MS
#define FLOWER_LAMP_CALIBRATION_MS 2000
#endif

#ifndef FLOWER_LAMP_SAMPLE_RATE_HZ
#define FLOWER_LAMP_SAMPLE_RATE_HZ 8000
#endif

#ifndef FLOWER_LAMP_DC_CENTER_ALPHA
#define FLOWER_LAMP_DC_CENTER_ALPHA 0.004f
#endif

#ifndef FLOWER_LAMP_PRESSURE_ATTACK_ALPHA
#define FLOWER_LAMP_PRESSURE_ATTACK_ALPHA 0.65f
#endif

#ifndef FLOWER_LAMP_PRESSURE_RELEASE_ALPHA
#define FLOWER_LAMP_PRESSURE_RELEASE_ALPHA 0.14f
#endif

#ifndef FLOWER_LAMP_BRIGHTNESS_ATTACK_ALPHA
#define FLOWER_LAMP_BRIGHTNESS_ATTACK_ALPHA 0.32f
#endif

#ifndef FLOWER_LAMP_BRIGHTNESS_RELEASE_ALPHA
#define FLOWER_LAMP_BRIGHTNESS_RELEASE_ALPHA 0.09f
#endif

#ifndef FLOWER_LAMP_CEILING_DECAY_ALPHA
#define FLOWER_LAMP_CEILING_DECAY_ALPHA 0.0012f
#endif

#ifndef FLOWER_LAMP_NOISE_GATE_MULTIPLIER
#define FLOWER_LAMP_NOISE_GATE_MULTIPLIER 0.6f
#endif

#ifndef FLOWER_LAMP_NOISE_GATE_OFFSET
#define FLOWER_LAMP_NOISE_GATE_OFFSET 3.0f
#endif

#ifndef FLOWER_LAMP_CEILING_HEADROOM_MULTIPLIER
#define FLOWER_LAMP_CEILING_HEADROOM_MULTIPLIER 5.5f
#endif

#ifndef FLOWER_LAMP_MIN_PRESSURE_RANGE
#define FLOWER_LAMP_MIN_PRESSURE_RANGE 24.0f
#endif

#ifndef FLOWER_LAMP_BUTTON_DEBOUNCE_MS
#define FLOWER_LAMP_BUTTON_DEBOUNCE_MS 35
#endif

#ifndef FLOWER_LAMP_BREATH_PERIOD_MS
#define FLOWER_LAMP_BREATH_PERIOD_MS 3200
#endif

constexpr int LAMP_PIN = FLOWER_LAMP_LAMP_PIN;
constexpr int MIC_PIN = FLOWER_LAMP_MIC_PIN;
constexpr int MODE_BUTTON_PIN = FLOWER_LAMP_MODE_BUTTON_PIN;

constexpr int PWM_FREQUENCY_HZ = FLOWER_LAMP_PWM_FREQUENCY_HZ;
constexpr int PWM_RESOLUTION_BITS = FLOWER_LAMP_PWM_RESOLUTION_BITS;
constexpr int PWM_MAX_DUTY = (1 << PWM_RESOLUTION_BITS) - 1;
constexpr int MAX_BRIGHTNESS_PERCENT = FLOWER_LAMP_MAX_BRIGHTNESS_PERCENT;
constexpr uint8_t BREATH_FLOOR_PERCENT = FLOWER_LAMP_BREATH_FLOOR_PERCENT;
constexpr uint8_t STEADY_BRIGHTNESS_PERCENT = FLOWER_LAMP_STEADY_BRIGHTNESS_PERCENT;

constexpr unsigned long SAMPLE_WINDOW_MS = FLOWER_LAMP_SAMPLE_WINDOW_MS;
constexpr unsigned long CALIBRATION_MS = FLOWER_LAMP_CALIBRATION_MS;
constexpr unsigned int SAMPLE_RATE_HZ = FLOWER_LAMP_SAMPLE_RATE_HZ;

constexpr float DC_CENTER_ALPHA = FLOWER_LAMP_DC_CENTER_ALPHA;
constexpr float PRESSURE_ATTACK_ALPHA = FLOWER_LAMP_PRESSURE_ATTACK_ALPHA;
constexpr float PRESSURE_RELEASE_ALPHA = FLOWER_LAMP_PRESSURE_RELEASE_ALPHA;
constexpr float BRIGHTNESS_ATTACK_ALPHA = FLOWER_LAMP_BRIGHTNESS_ATTACK_ALPHA;
constexpr float BRIGHTNESS_RELEASE_ALPHA = FLOWER_LAMP_BRIGHTNESS_RELEASE_ALPHA;
constexpr float CEILING_DECAY_ALPHA = FLOWER_LAMP_CEILING_DECAY_ALPHA;
constexpr float NOISE_GATE_MULTIPLIER = FLOWER_LAMP_NOISE_GATE_MULTIPLIER;
constexpr float NOISE_GATE_OFFSET = FLOWER_LAMP_NOISE_GATE_OFFSET;
constexpr float CEILING_HEADROOM_MULTIPLIER = FLOWER_LAMP_CEILING_HEADROOM_MULTIPLIER;
constexpr float MIN_PRESSURE_RANGE = FLOWER_LAMP_MIN_PRESSURE_RANGE;

constexpr unsigned long BUTTON_DEBOUNCE_MS = FLOWER_LAMP_BUTTON_DEBOUNCE_MS;
constexpr unsigned long BREATH_PERIOD_MS = FLOWER_LAMP_BREATH_PERIOD_MS;

static_assert(SAMPLE_RATE_HZ > 0, "sample_rate_hz must be greater than 0");
