#pragma once

#include <stdint.h>

#if __has_include("FlowerLampConfig.generated.h")
#include "FlowerLampConfig.generated.h"
#endif

#ifndef FLOWER_LAMP_LAMP_PIN
#define FLOWER_LAMP_LAMP_PIN 23
#endif

#ifndef FLOWER_LAMP_MIC_PIN
#define FLOWER_LAMP_MIC_PIN 34
#endif

#ifndef FLOWER_LAMP_MODE_BUTTON_PIN
#define FLOWER_LAMP_MODE_BUTTON_PIN 27
#endif

#ifndef FLOWER_LAMP_PWM_FREQUENCY_HZ
#define FLOWER_LAMP_PWM_FREQUENCY_HZ 1000
#endif

#ifndef FLOWER_LAMP_PWM_RESOLUTION_BITS
#define FLOWER_LAMP_PWM_RESOLUTION_BITS 8
#endif

#ifndef FLOWER_LAMP_MAX_BRIGHTNESS_PERCENT
#define FLOWER_LAMP_MAX_BRIGHTNESS_PERCENT 98
#endif

#ifndef FLOWER_LAMP_BREATH_FLOOR_PERCENT
#define FLOWER_LAMP_BREATH_FLOOR_PERCENT 1
#endif

#ifndef FLOWER_LAMP_BREATH_PEAK_PERCENT
#define FLOWER_LAMP_BREATH_PEAK_PERCENT 35
#endif

#ifndef FLOWER_LAMP_STEADY_BRIGHTNESS_PERCENT
#define FLOWER_LAMP_STEADY_BRIGHTNESS_PERCENT 18
#endif

#ifndef FLOWER_LAMP_SAMPLE_WINDOW_MS
#define FLOWER_LAMP_SAMPLE_WINDOW_MS 25
#endif

#ifndef FLOWER_LAMP_CALIBRATION_MS
#define FLOWER_LAMP_CALIBRATION_MS 2000
#endif

#ifndef FLOWER_LAMP_NOISE_FLOOR_STDDEV_MULTIPLIER
#define FLOWER_LAMP_NOISE_FLOOR_STDDEV_MULTIPLIER 1.5f
#endif

#ifndef FLOWER_LAMP_NOISE_FLOOR_MARGIN_RMS
#define FLOWER_LAMP_NOISE_FLOOR_MARGIN_RMS 3.0f
#endif

#ifndef FLOWER_LAMP_NOISE_FLOOR_ADAPT_ALPHA
#define FLOWER_LAMP_NOISE_FLOOR_ADAPT_ALPHA 0.02f
#endif

#ifndef FLOWER_LAMP_NOISE_FLOOR_ADAPT_MAX_RISE_RMS
#define FLOWER_LAMP_NOISE_FLOOR_ADAPT_MAX_RISE_RMS 40.0f
#endif

#ifndef FLOWER_LAMP_SOUND_REACTIVE_PRE_CALIBRATION_SETTLE_MS
#define FLOWER_LAMP_SOUND_REACTIVE_PRE_CALIBRATION_SETTLE_MS 1200
#endif

#ifndef FLOWER_LAMP_SOUND_REACTIVE_SETTLE_MS
#define FLOWER_LAMP_SOUND_REACTIVE_SETTLE_MS 400
#endif

#ifndef FLOWER_LAMP_SAMPLE_RATE_HZ
#define FLOWER_LAMP_SAMPLE_RATE_HZ 8000
#endif

#ifndef FLOWER_LAMP_DC_CENTER_ALPHA
#define FLOWER_LAMP_DC_CENTER_ALPHA 0.004f
#endif

#ifndef FLOWER_LAMP_PRESSURE_ATTACK_ALPHA
#define FLOWER_LAMP_PRESSURE_ATTACK_ALPHA 0.65f
#endif

#ifndef FLOWER_LAMP_PRESSURE_RELEASE_ALPHA
#define FLOWER_LAMP_PRESSURE_RELEASE_ALPHA 0.14f
#endif

#ifndef FLOWER_LAMP_BRIGHTNESS_ATTACK_ALPHA
#define FLOWER_LAMP_BRIGHTNESS_ATTACK_ALPHA 0.32f
#endif

#ifndef FLOWER_LAMP_BRIGHTNESS_RELEASE_ALPHA
#define FLOWER_LAMP_BRIGHTNESS_RELEASE_ALPHA 0.09f
#endif

#ifndef FLOWER_LAMP_CEILING_DECAY_ALPHA
#define FLOWER_LAMP_CEILING_DECAY_ALPHA 0.0012f
#endif

#ifndef FLOWER_LAMP_NOISE_GATE_MULTIPLIER
#define FLOWER_LAMP_NOISE_GATE_MULTIPLIER 0.6f
#endif

#ifndef FLOWER_LAMP_NOISE_GATE_OFFSET
#define FLOWER_LAMP_NOISE_GATE_OFFSET 3.0f
#endif

#ifndef FLOWER_LAMP_CEILING_HEADROOM_MULTIPLIER
#define FLOWER_LAMP_CEILING_HEADROOM_MULTIPLIER 5.5f
#endif

#ifndef FLOWER_LAMP_MIN_PRESSURE_RANGE
#define FLOWER_LAMP_MIN_PRESSURE_RANGE 24.0f
#endif

#ifndef FLOWER_LAMP_LOUDNESS_ACTIVATION_RMS
#define FLOWER_LAMP_LOUDNESS_ACTIVATION_RMS 6.0f
#endif

#ifndef FLOWER_LAMP_LOUDNESS_FIRST_LEVEL_RMS
#define FLOWER_LAMP_LOUDNESS_FIRST_LEVEL_RMS 3.0f
#endif

#ifndef FLOWER_LAMP_LOUDNESS_LEVEL_COUNT
#define FLOWER_LAMP_LOUDNESS_LEVEL_COUNT 11
#endif

#ifndef FLOWER_LAMP_BRIGHTNESS_LEVEL_COUNT
#define FLOWER_LAMP_BRIGHTNESS_LEVEL_COUNT 8
#endif

#ifndef FLOWER_LAMP_LOUDNESS_HYSTERESIS_LEVELS
#define FLOWER_LAMP_LOUDNESS_HYSTERESIS_LEVELS 0.15f
#endif

#ifndef FLOWER_LAMP_BRIGHTNESS_LEVEL_GAMMA
#define FLOWER_LAMP_BRIGHTNESS_LEVEL_GAMMA 2.4f
#endif

#ifndef FLOWER_LAMP_TRANSIENT_ENABLED
#define FLOWER_LAMP_TRANSIENT_ENABLED 0
#endif

#ifndef FLOWER_LAMP_TRANSIENT_BASELINE_ALPHA
#define FLOWER_LAMP_TRANSIENT_BASELINE_ALPHA 0.04f
#endif

#ifndef FLOWER_LAMP_TRANSIENT_THRESHOLD_MULTIPLIER
#define FLOWER_LAMP_TRANSIENT_THRESHOLD_MULTIPLIER 1.8f
#endif

#ifndef FLOWER_LAMP_TRANSIENT_MIN_RISE_RMS
#define FLOWER_LAMP_TRANSIENT_MIN_RISE_RMS 8.0f
#endif

#ifndef FLOWER_LAMP_TRANSIENT_PULSE_PERCENT
#define FLOWER_LAMP_TRANSIENT_PULSE_PERCENT 98
#endif

#ifndef FLOWER_LAMP_TRANSIENT_PULSE_DECAY_ALPHA
#define FLOWER_LAMP_TRANSIENT_PULSE_DECAY_ALPHA 0.30f
#endif

#ifndef FLOWER_LAMP_TRANSIENT_COOLDOWN_MS
#define FLOWER_LAMP_TRANSIENT_COOLDOWN_MS 90
#endif

#ifndef FLOWER_LAMP_BUTTON_DEBOUNCE_MS
#define FLOWER_LAMP_BUTTON_DEBOUNCE_MS 35
#endif

#ifndef FLOWER_LAMP_BREATH_PERIOD_MS
#define FLOWER_LAMP_BREATH_PERIOD_MS 3200
#endif

#ifndef FLOWER_LAMP_DEBUG_SERIAL_ENABLED
#define FLOWER_LAMP_DEBUG_SERIAL_ENABLED 0
#endif

#ifndef FLOWER_LAMP_DEBUG_SERIAL_INTERVAL_MS
#define FLOWER_LAMP_DEBUG_SERIAL_INTERVAL_MS 500
#endif

constexpr int LAMP_PIN = FLOWER_LAMP_LAMP_PIN;
constexpr int MIC_PIN = FLOWER_LAMP_MIC_PIN;
constexpr int MODE_BUTTON_PIN = FLOWER_LAMP_MODE_BUTTON_PIN;

constexpr int PWM_FREQUENCY_HZ = FLOWER_LAMP_PWM_FREQUENCY_HZ;
constexpr int PWM_RESOLUTION_BITS = FLOWER_LAMP_PWM_RESOLUTION_BITS;
constexpr int PWM_MAX_DUTY = (1 << PWM_RESOLUTION_BITS) - 1;
constexpr int MAX_BRIGHTNESS_PERCENT = FLOWER_LAMP_MAX_BRIGHTNESS_PERCENT;
constexpr uint8_t BREATH_FLOOR_PERCENT = FLOWER_LAMP_BREATH_FLOOR_PERCENT;
constexpr uint8_t BREATH_PEAK_PERCENT = FLOWER_LAMP_BREATH_PEAK_PERCENT;
constexpr uint8_t STEADY_BRIGHTNESS_PERCENT = FLOWER_LAMP_STEADY_BRIGHTNESS_PERCENT;

constexpr unsigned long SAMPLE_WINDOW_MS = FLOWER_LAMP_SAMPLE_WINDOW_MS;
constexpr unsigned long CALIBRATION_MS = FLOWER_LAMP_CALIBRATION_MS;
constexpr float NOISE_FLOOR_STDDEV_MULTIPLIER = FLOWER_LAMP_NOISE_FLOOR_STDDEV_MULTIPLIER;
constexpr float NOISE_FLOOR_MARGIN_RMS = FLOWER_LAMP_NOISE_FLOOR_MARGIN_RMS;
constexpr float NOISE_FLOOR_ADAPT_ALPHA = FLOWER_LAMP_NOISE_FLOOR_ADAPT_ALPHA;
constexpr float NOISE_FLOOR_ADAPT_MAX_RISE_RMS = FLOWER_LAMP_NOISE_FLOOR_ADAPT_MAX_RISE_RMS;
constexpr unsigned long SOUND_REACTIVE_PRE_CALIBRATION_SETTLE_MS = FLOWER_LAMP_SOUND_REACTIVE_PRE_CALIBRATION_SETTLE_MS;
constexpr unsigned long SOUND_REACTIVE_SETTLE_MS = FLOWER_LAMP_SOUND_REACTIVE_SETTLE_MS;
constexpr unsigned int SAMPLE_RATE_HZ = FLOWER_LAMP_SAMPLE_RATE_HZ;

constexpr float DC_CENTER_ALPHA = FLOWER_LAMP_DC_CENTER_ALPHA;
constexpr float PRESSURE_ATTACK_ALPHA = FLOWER_LAMP_PRESSURE_ATTACK_ALPHA;
constexpr float PRESSURE_RELEASE_ALPHA = FLOWER_LAMP_PRESSURE_RELEASE_ALPHA;
constexpr float BRIGHTNESS_ATTACK_ALPHA = FLOWER_LAMP_BRIGHTNESS_ATTACK_ALPHA;
constexpr float BRIGHTNESS_RELEASE_ALPHA = FLOWER_LAMP_BRIGHTNESS_RELEASE_ALPHA;
constexpr float CEILING_DECAY_ALPHA = FLOWER_LAMP_CEILING_DECAY_ALPHA;
constexpr float NOISE_GATE_MULTIPLIER = FLOWER_LAMP_NOISE_GATE_MULTIPLIER;
constexpr float NOISE_GATE_OFFSET = FLOWER_LAMP_NOISE_GATE_OFFSET;
constexpr float CEILING_HEADROOM_MULTIPLIER = FLOWER_LAMP_CEILING_HEADROOM_MULTIPLIER;
constexpr float MIN_PRESSURE_RANGE = FLOWER_LAMP_MIN_PRESSURE_RANGE;
constexpr float LOUDNESS_ACTIVATION_RMS = FLOWER_LAMP_LOUDNESS_ACTIVATION_RMS;
constexpr float LOUDNESS_FIRST_LEVEL_RMS = FLOWER_LAMP_LOUDNESS_FIRST_LEVEL_RMS;

constexpr int LOUDNESS_LEVEL_COUNT = FLOWER_LAMP_LOUDNESS_LEVEL_COUNT;
constexpr int BRIGHTNESS_LEVEL_COUNT = FLOWER_LAMP_BRIGHTNESS_LEVEL_COUNT;
constexpr float LOUDNESS_HYSTERESIS_LEVELS = FLOWER_LAMP_LOUDNESS_HYSTERESIS_LEVELS;
constexpr float BRIGHTNESS_LEVEL_GAMMA = FLOWER_LAMP_BRIGHTNESS_LEVEL_GAMMA;

constexpr int TRANSIENT_ENABLED = FLOWER_LAMP_TRANSIENT_ENABLED;
constexpr float TRANSIENT_BASELINE_ALPHA = FLOWER_LAMP_TRANSIENT_BASELINE_ALPHA;
constexpr float TRANSIENT_THRESHOLD_MULTIPLIER = FLOWER_LAMP_TRANSIENT_THRESHOLD_MULTIPLIER;
constexpr float TRANSIENT_MIN_RISE_RMS = FLOWER_LAMP_TRANSIENT_MIN_RISE_RMS;
constexpr int TRANSIENT_PULSE_PERCENT = FLOWER_LAMP_TRANSIENT_PULSE_PERCENT;
constexpr float TRANSIENT_PULSE_DECAY_ALPHA = FLOWER_LAMP_TRANSIENT_PULSE_DECAY_ALPHA;
constexpr unsigned long TRANSIENT_COOLDOWN_MS = FLOWER_LAMP_TRANSIENT_COOLDOWN_MS;

constexpr unsigned long BUTTON_DEBOUNCE_MS = FLOWER_LAMP_BUTTON_DEBOUNCE_MS;
constexpr unsigned long BREATH_PERIOD_MS = FLOWER_LAMP_BREATH_PERIOD_MS;
constexpr int DEBUG_SERIAL_ENABLED = FLOWER_LAMP_DEBUG_SERIAL_ENABLED;
constexpr unsigned long DEBUG_SERIAL_INTERVAL_MS = FLOWER_LAMP_DEBUG_SERIAL_INTERVAL_MS;

static_assert(SAMPLE_RATE_HZ > 0, "sample_rate_hz must be greater than 0");
static_assert(BREATH_PEAK_PERCENT >= BREATH_FLOOR_PERCENT, "breath_peak_percent must be >= breath_floor_percent");
static_assert(NOISE_FLOOR_STDDEV_MULTIPLIER >= 0.0f, "noise_floor_stddev_multiplier must be 0 or greater");
static_assert(NOISE_FLOOR_MARGIN_RMS >= 0.0f, "noise_floor_margin_rms must be 0 or greater");
static_assert(NOISE_FLOOR_ADAPT_ALPHA >= 0.0f && NOISE_FLOOR_ADAPT_ALPHA <= 1.0f, "noise_floor_adapt_alpha must be in 0..1");
static_assert(NOISE_FLOOR_ADAPT_MAX_RISE_RMS >= 0.0f, "noise_floor_adapt_max_rise_rms must be 0 or greater");
static_assert(LOUDNESS_LEVEL_COUNT >= 2, "loudness_level_count must be at least 2");
static_assert(BRIGHTNESS_LEVEL_COUNT >= 2, "brightness_level_count must be at least 2");
static_assert(LOUDNESS_ACTIVATION_RMS >= 0.0f, "loudness_activation_rms must be 0 or greater");
static_assert(LOUDNESS_FIRST_LEVEL_RMS >= 0.0f, "loudness_first_level_rms must be 0 or greater");
static_assert(TRANSIENT_ENABLED == 0 || TRANSIENT_ENABLED == 1, "transient_enabled must be 0 or 1");
static_assert(TRANSIENT_BASELINE_ALPHA >= 0.0f && TRANSIENT_BASELINE_ALPHA <= 1.0f, "transient_baseline_alpha must be in 0..1");
static_assert(TRANSIENT_THRESHOLD_MULTIPLIER >= 1.0f, "transient_threshold_multiplier must be at least 1");
static_assert(TRANSIENT_MIN_RISE_RMS >= 0.0f, "transient_min_rise_rms must be 0 or greater");
static_assert(TRANSIENT_PULSE_DECAY_ALPHA >= 0.0f && TRANSIENT_PULSE_DECAY_ALPHA <= 1.0f, "transient_pulse_decay_alpha must be in 0..1");
